### ISSUE TITLE
Sort by size broken

### ISSUE THREAD

**Issue by subworx** [FranjeGueje/DeckTools#2]
Hi,

thank you for this tool, I use it regularly and love it.

In version 2.2, sorting by "Use on disk" is broken. The numbers are just an example, but it sorts the numbers without looking for the size unit:

Expected sorting: 12K, 140K, 11M, 12M, 16M, 111M, 117M, 138M, 1,6G.

Actual sorting: 1.6G, 11M, 111M, 117M, 12K, 12M, 138M, 140K, 16M.

Possible solutions: 
- "Expand" the numbers to their KB value, sort, then convert the unit back. For example, 140K = 140K, 12M = 12000K, 138M = 138000K, 1.6G = 1600000K. Sort by these numbers, then convert back to M/G. 
- Leave out the human-readable parameter when checking for files, but divide by 1000 (M) or 1000000 (G) before displaying.

Thank you very much :)

**Comment by FranjeGueje** [comment]
Thanks for writing!

Yes, this is a good enhancing. But the problem is zenity (the utility that show content on windows), because zenity shorts alphabetically. When I short this column the short alphabetically...
1 before that 2, 2 before that 3,...
GB, MB, ... it's the same, zenity order by the first number (or second if the first is the same).

I'd like thinking about this.

Thanks for give your help!

**Comment by FranjeGueje** [comment]
Hi!
I've just launched the 2.3 version. I've added a new column to order by disk space.
It's possible that your request is solved.

Best regards!

**Comment by subworx** [comment]
Hey :)

Just gave it a try and sorting by the new column "Sort" sorts the games by their real size, exactly as expected. Thank you :)

I have no idea how you construct the letter/number combinations, but also I don't care 😉

Also noticed the English translation has been slightly improved, great to see.

Thank you very much for your work on this :)
